name: check

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-20.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: mpi and mkl
      run: sudo apt-get install -y mpi-default-dev intel-mkl
    - name: pybind11
      working-directory: ${{github.workspace}}
      run: git clone https://github.com/pybind/pybind11.git
    - name: fire
      working-directory: ${{github.workspace}}/include
      run: wget https://raw.githubusercontent.com/kongaskristjan/fire-hpp/master/include/fire-hpp/fire.hpp
    - name: build directory
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{github.workspace}}
    - name: make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 20
    - name: test simple_test
      working-directory: ${{runner.workspace}}/build
      run: ./simple_test
    - name: test python
      working-directory: ${{runner.workspace}}/build
      run: python -c 'import TAT; TAT()'
